### PR TITLE
Update strlen.adoc

### PR DESCRIPTION
**Pull request by topperc**
orc.b produces all-ones if there are no NUL bytes.

### CODE REVIEW

**Comment by ptomsich** [comment]
@kasanovic How do you want us to handle these obvious corrections that come in during public review? Should we frequently generate new versions and update, so reviewers won't file duplicate comments? This obviously also applies to #140 ...

**Comment by ben-marshall** [comment]
Joining in this thread because I'm having / going to have the same problem with the scalar cryptography specification. So far, I've been grouping changes together and doing at most one release a week so people don't get fatigued and there aren't N versions of the spec for N different small fixes.

**Comment by kasanovic** [comment]
Normally, for uncontroversial improvements to text, i.e., typos, fixing errors, but no actual changes to intended spec, updating current version in repo as we go through public review is fine with only git hash used to identify these incremental versions.   This doc flow is probably difficult to build for many so could be useful to regenerate pdf every so often, when enough substantial improvements to text have been made.   We have to accept comments on any version we put out regardless.

**Comment by ptomsich** [comment]
> Normally, for uncontroversial improvements to text, i.e., typos, fixing errors, but no actual changes to intended spec, updating current version in repo as we go through public review is fine with only git hash used to identify these incremental versions. This doc flow is probably difficult to build for many so could be useful to regenerate pdf every so often, when enough substantial improvements to text have been made. We have to accept comments on any version we put out regardless.

The doc flow is easy enough that we had automated it with Gitlab's CI, while the document was being converted to ASCIIdoc.  The gitlab-ci control file is still in this repository and only needs to be ported to Github's CI (extra credit for patching Wavedrom, if the version pulled in by default has the all-zeros bug).

For the time being, I'll make some time to merge uncontroversial PRs once or twice a week.

**Comment by ptomsich** [comment]
@topperc Could you rebase to the current-most top-of-trunk?

**Comment by topperc** [comment]
I think this was already fixed.

**Pull request closed without merging**
