### PR TITLE
Fix desc for signextend

### PR DESCRIPTION
**Pull request by ZenithalHourlyRate**
Ref to a34d4626 zbb: remove zext.w
Ref to a8ad7a8a bitmanip/overview: Remove sext.w/zext.b (pseudo-instructions)

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
Side note: a different style of fix already exists at #162. Do not know which one is acceptable.
Cc @cmuellner

**Comment by jim-wilson** [comment]
This document is effectively dead.  If there are problems with the ISA docs then they need to be fixed, but we don't really need any fixes here.

**Comment by ZenithalHourlyRate** [comment]
> This document is effectively dead.

I do not understand what you meant. Is this repo deprecated and no longer the official repo for bitmanip extension? If it is, I can not find another official place that contains bitmanip spec. The unprivileged part of [riscv/riscv-isa-manual](https://github.com/riscv/riscv-isa-manual) does not contain the bitmanip extension; also, https://riscv.org/technical/specifications/ still points to this repo.

> If there are problems with the ISA docs

These typos do affect the ISA doc. Typos and out-dated description would cause confusion when people are reading or implementing the spec, thus they should be fixed.

**Comment by cmuellner** [comment]
Thanks for reporting!
I think this change is correct but has no significant impact on the specification (so no urgent need for action).

The Bitmanip ISA spec in its current form is ratified.
That does not mean that there are no mistakes (there are a few more PRs that provide fixes).

RVI currently has no Bitmanip TG, so this document is owned by the governing unpriv IC.
I can't speak for that committee, but I know that they are working on many other topics as well in parallel, so it might take some time until someone will find time to decide what to do with issues like this one (e.g. create an errata document or a dot-release).

**Comment by ZenithalHourlyRate** [comment]
> I think this change has no significant impact on the specification (so no urgent need for action).

Yeah I understand that

> so it might take some time until someone will find time to decide what to do with issues like this one

I totally agree. I had expected to wait when I saw a lot of pending PRs.

**Review by aswaterman — APPROVED** [review]

**Pull request merged**
